version: "3.9"

services:
  k0s:
    image: 'docker.io/k0sproject/k0s:v1.27.1-k0s.0' # docker.io/k0sproject/k0s:latest
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
    restart: "no"
    privileged: false
    volumes:
      - ./secrets:/mnt
    entrypoint: ["/bin/bash", "-c"]
    command:
    - |
      cd /mnt
      apk add openssl
      openssl genrsa -out ca.key 2048
      openssl req -x509 -new -nodes -key ca.key -sha256 -days 36500 -out ca.crt -subj "/CN=Custom CA"
      #k0s token pre-shared --role controller --cert /mnt/ca.crt --url https://k0s:6443/ --out /tmp
      #mv /tmp/bootstrap-token-*.yaml secret_controller.yaml
      #mv /tmp/token* controller.token
      #k0s token pre-shared --role worker --cert /mnt/ca.crt --url https://127.0.0.1:6443/ --out /tmp
      #mv /tmp/bootstrap-token-*.yaml secret_worker.yaml
      #mv /tmp/token* worker.token
      # https://etcd.io/docs/v3.3/op-guide/clustering/#dns-discovery
      # curl -s https://discovery.etcd.io/new?size=3 > ETCD_DISCOVERY
